# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jobs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\njobs.proto\x12\x04jobs\"\x1f\n\rGetJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\"0\n\x0eGetJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"$\n\x10\x43reateJobRequest\x12\x10\n\x08job_name\x18\x01 \x01(\t\"#\n\x11\x43reateJobResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x7f\n\nJobService\x12\x33\n\x06GetJob\x12\x13.jobs.GetJobRequest\x1a\x14.jobs.GetJobResponse\x12<\n\tCreateJob\x12\x16.jobs.CreateJobRequest\x1a\x17.jobs.CreateJobResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jobs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETJOBREQUEST._serialized_start=20
  _GETJOBREQUEST._serialized_end=51
  _GETJOBRESPONSE._serialized_start=53
  _GETJOBRESPONSE._serialized_end=101
  _CREATEJOBREQUEST._serialized_start=103
  _CREATEJOBREQUEST._serialized_end=139
  _CREATEJOBRESPONSE._serialized_start=141
  _CREATEJOBRESPONSE._serialized_end=176
  _JOBSERVICE._serialized_start=178
  _JOBSERVICE._serialized_end=305
# @@protoc_insertion_point(module_scope)
