---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-service
  namespace: microservices
  labels:
    app: pipeline-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipeline-service
  template:
    metadata:
      labels:
        app: pipeline-service
    spec:
      containers:
      - name: pipeline-service
        image: pipeline-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50053
          name: grpc
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 50053
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 50053
          initialDelaySeconds: 5
          periodSeconds: 5
