# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\x05\":\n\x12\x43reateUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x04user\x18\x02 \x01(\x0b\x32\x05.User2R\n\x0bUserService\x12(\n\nCreateUser\x12\x05.User\x1a\x13.CreateUserResponse\x12\x19\n\x07GetUser\x12\x07.UserId\x1a\x05.Userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=15
  _globals['_USER']._serialized_end=62
  _globals['_USERID']._serialized_start=64
  _globals['_USERID']._serialized_end=84
  _globals['_CREATEUSERRESPONSE']._serialized_start=86
  _globals['_CREATEUSERRESPONSE']._serialized_end=144
  _globals['_USERSERVICE']._serialized_start=146
  _globals['_USERSERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
