# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pipelines.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'pipelines.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpipelines.proto\x12\tpipelines\")\n\x12GetPipelineRequest\x12\x13\n\x0bpipeline_id\x18\x01 \x01(\x05\":\n\x13GetPipelineResponse\x12\x13\n\x0bpipeline_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\".\n\x15\x43reatePipelineRequest\x12\x15\n\rpipeline_name\x18\x01 \x01(\t\"(\n\x16\x43reatePipelineResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb6\x01\n\x0fPipelineService\x12L\n\x0bGetPipeline\x12\x1d.pipelines.GetPipelineRequest\x1a\x1e.pipelines.GetPipelineResponse\x12U\n\x0e\x43reatePipeline\x12 .pipelines.CreatePipelineRequest\x1a!.pipelines.CreatePipelineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipelines_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPIPELINEREQUEST']._serialized_start=30
  _globals['_GETPIPELINEREQUEST']._serialized_end=71
  _globals['_GETPIPELINERESPONSE']._serialized_start=73
  _globals['_GETPIPELINERESPONSE']._serialized_end=131
  _globals['_CREATEPIPELINEREQUEST']._serialized_start=133
  _globals['_CREATEPIPELINEREQUEST']._serialized_end=179
  _globals['_CREATEPIPELINERESPONSE']._serialized_start=181
  _globals['_CREATEPIPELINERESPONSE']._serialized_end=221
  _globals['_PIPELINESERVICE']._serialized_start=224
  _globals['_PIPELINESERVICE']._serialized_end=406
# @@protoc_insertion_point(module_scope)
