# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pipelines_pb2 as pipelines__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pipelines_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PipelineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPipeline = channel.unary_unary(
                '/pipelines.PipelineService/GetPipeline',
                request_serializer=pipelines__pb2.GetPipelineRequest.SerializeToString,
                response_deserializer=pipelines__pb2.GetPipelineResponse.FromString,
                _registered_method=True)
        self.CreatePipeline = channel.unary_unary(
                '/pipelines.PipelineService/CreatePipeline',
                request_serializer=pipelines__pb2.CreatePipelineRequest.SerializeToString,
                response_deserializer=pipelines__pb2.CreatePipelineResponse.FromString,
                _registered_method=True)


class PipelineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPipeline,
                    request_deserializer=pipelines__pb2.GetPipelineRequest.FromString,
                    response_serializer=pipelines__pb2.GetPipelineResponse.SerializeToString,
            ),
            'CreatePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePipeline,
                    request_deserializer=pipelines__pb2.CreatePipelineRequest.FromString,
                    response_serializer=pipelines__pb2.CreatePipelineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipelines.PipelineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipelines.PipelineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipelineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipelines.PipelineService/GetPipeline',
            pipelines__pb2.GetPipelineRequest.SerializeToString,
            pipelines__pb2.GetPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipelines.PipelineService/CreatePipeline',
            pipelines__pb2.CreatePipelineRequest.SerializeToString,
            pipelines__pb2.CreatePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
