---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: microservices
  labels:
    app: users-service
spec:
  selector:
    app: users-service
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  type: ClusterIP