---
apiVersion: v1
kind: Service
metadata:
  name: jobs-service
  namespace: microservices
  labels:
    app: jobs-service
spec:
  selector:
    app: jobs-service
  ports:
  - port: 50052
    targetPort: 50052
    protocol: TCP
    name: grpc
  type: ClusterIP